# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CO38-P6xP9xgP6rCuAxKQmGHSOrXOmUu
"""

# NAMA    :HENGKY RYANTO SIHOMBING
# NIM     :4232401055
# TANGAAL :9/22/2026

# B_PRATIKUM

#B1

#1
#penjumlahan
a= 10
b= 10
c= a+b

print(c)

#pengurangan
a= 10
b= 3
c= a-b

print(c)

#perkalian
a= 10
b= 10
c= a*b

print(c)

#pembagian
a= 5
b= 15
c= a/b

print(c)

#hasil_pembagian_bulat
a=15
b=5
c=a//b

print(c)

#modulus
a=15
b=25
c=a%b
print(c)



#2

nilai_ujian=int(40)

print(40, nilai_ujian>=60)

nilai_ujian=int(90)
print(90, nilai_ujian>=60)



#3
umur=int(20)
punya_sim=("True")
izin_mengemudi=(umur >= 17) and punya_sim
print("izin mengemudi:", izin_mengemudi)

umur=int(20)
punya_sim=("False")
izin_mengemudi=(umur >= 17) and punya_sim
print("izin mengemudi:", izin_mengemudi)


umur=int(17)
punya_sim=("False")
izin_mengemudi=(umur >= 17) and punya_sim
print("izin mengemudi:", izin_mengemudi)

umur=int(17)
punya_sim=("False")
izin_mengemudi=(umur >= 17) and punya_sim
print("izin mengemudi:", izin_mengemudi)



#B2

#4
energi_input= float(input(1800))
energi_output= float(input(900))

efisiensi= (energi_output/energi_input)*100

print(f"Efisisensi energi={efisiensi:.2f}%")


#5
suhu_boiler_Celcius= float(input(500))
beban_operasi_persen= float(input(80))
perlu_maintenance=(suhu_boiler_Celcius > 550) or (beban_operasi_persen> 95)
print(f"perlu maintanance: {perlu_maintenance}")

